version: "3.9"

services:
  mysql:
    container_name: codemeter-db
    image: mysql:8
    ports:
      - 13306:3306
    env_file:
      - .db_env
    environment:
      MYSQL_ROOT_HOST: '%'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
