version: "3.9"

services:
  mysql:
    container_name: codemeter-db
    image: mysql:8
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: codemeter
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
