export enum Reference {
  TV_WATCH_TIME = 'TV_CARBON_EMISSION_PER_HOUR',
  DRIVING_DISTANCE = 'CARBON_EMISSIONS_OF_AVERAGE_PASSENGER_IN_EUROPE',
  SUBWAY_DISTANCE = 'SUBWAY_TRAVEL_DISTANCE_KILOMETER_PER_GCO2E',
  APPLE_PRODUCTION = 'APPLE_PRODUCTION_PER_GCO2E',
}
