export enum Status {
  SUCCESS = 0,
  COMPILE_ERROR = 4,
  RUNTIME_ERROR = 1,
  TIME_LIMIT_EXCEEDED = 2,
  // TODO: 추후 기능 확장 가능
  // MEMORY_LIMIT_EXCEEDED = 3,
}

export enum ExecutionStatus {
  SUCCESS = 'SUCCESS',
  COMPILE_ERROR = 'COMPILE_ERROR',
  RUNTIME_ERROR = 'RUNTIME_ERROR',
  TIME_LIMIT_EXCEEDED = 'TIME_LIMIT_EXCEEDED',
  // TODO: 추후 기능 확장 가능
  // MEMORY_LIMIT_EXCEEDED = 'MEMORY_LIMIT_EXCEEDED',
}
